In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [2]:
train1 = pd.read_csv('train_pop_per_pvz_by_iso.csv')
train2 = pd.read_csv('train_nearest_neighbor_distance.csv')
train3 = pd.read_csv('train_with_selected_commercial_density.csv')
train4 = pd.read_csv('train_landuse.csv')
train5 = pd.read_csv('train_metro_count_per_pvz.csv')


data = pd.merge(train1, train2, on = ['id', 'sales_per_month', 'region', 'locality', 'x', 'y', 'people_iso_3', 'people_iso_5', 'people_iso_10', 'people_iso_15', 'people_iso_30', 'type'])
data = pd.merge(data, train3, on = ['id', 'sales_per_month', 'region', 'locality', 'x', 'y', 'people_iso_3', 'people_iso_5', 'people_iso_10', 'people_iso_15', 'people_iso_30', 'type'])
data = pd.merge(data, train4, on = ['id', 'sales_per_month', 'region', 'locality', 'x', 'y', 'people_iso_3', 'people_iso_5', 'people_iso_10', 'people_iso_15', 'people_iso_30', 'type'])
data = pd.merge(data, train5, on = ['id', 'sales_per_month', 'region', 'locality', 'x', 'y', 'people_iso_3', 'people_iso_5', 'people_iso_10', 'people_iso_15', 'people_iso_30', 'type'])

list_idx_train = list(data.id)

data.fclass.fillna('unknown', inplace=True) 
data

,id,sales_per_month,region,locality,x,y,people_iso_3,people_iso_5,people_iso_10,people_iso_15,...,commercial_density_300,commercial_density_500,geometry,index_right,fclass,count_railway_station_iso_3,count_railway_station_iso_5,count_railway_station_iso_10,count_railway_station_iso_15,count_railway_station_iso_30
0,18398,2538.0,Челябинская область,Озерск,60.692229,55.761933,971,2093,10439,23027,...,19,28,POINT (60.692229 55.761933),NaN,unknown,0.0,0.0,0.0,0.0,0.0
1,14532,1645.0,Москва,Москва,37.678559,55.702931,840,2329,15949,35836,...,5,32,POINT (37.678559 55.702931),598516.0,residential,0.0,0.0,0.0,1.0,3.0
2,23801,3176.0,Липецкая область,Липецк,39.524007,52.589588,690,4012,22279,47864,...,13,33,POINT (39.524007 52.589588),777617.0,residential,0.0,0.0,0.0,0.0,0.0
3,9791,4759.0,Краснодарский край,посёлок городского типа Сириус,39.957405,43.414255,49,515,2699,3710,...,8,12,POINT (39.957405 43.414255),3681669.0,residential,0.0,0.0,0.0,0.0,1.0
4,3004,2051.0,Тюменская область,Сургут,73.450188,61.237837,1416,5619,23135,50801,...,38,74,POINT (73.450188 61.237837),4153109.0,residential,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8581,9396,2639.0,Тюменская область,Ноябрьск,75.438110,63.196350,486,2271,11123,24130,...,14,30,POINT (75.43811 63.19635),4145844.0,residential,0.0,0.0,0.0,0.0,0.0
8582,20106,2274.0,Московская область,Подольск,37.536210,55.421086,870,2170,12298,32230,...,17,24,POINT (37.53621 55.421086),603564.0,residential,0.0,0.0,0.0,0.0,0.0
8583,7559,2156.0,Волгоградская область,Волжский,44.773472,48.769915,285,369,3396,12123,...,0,0,POINT (44.773472 48.769915),3789298.0,residential,0.0,0.0,0.0,0.0,0.0
8584,15471,1427.0,Минск,Минск,27.555579,53.921064,645,1735,11585,21950,...,21,49,POINT (27.555579 53.921064),101529.0,residential,0.0,0.0,0.0,0.0,1.0
8585,16043,1952.0,Москва,Москва,37.417553,55.861494,1531,2206,18152,40219,...,2,13,POINT (37.417553 55.861494),595780.0,residential,0.0,0.0,0.0,0.0,1.0

In [3]:
test1 = pd.read_csv('test_pop_per_pvz_by_iso.csv')
test2 = pd.read_csv('test_nearest_neighbor_distance.csv')
test3 = pd.read_csv('test_with_selected_commercial_density.csv')
test4 = pd.read_csv('test_landuse.csv')
test5 = pd.read_csv('test_metro_count_per_pvz.csv')



test = pd.merge(test1, test2, on = ['id', 'sales_per_month', 'region', 'locality', 'x', 'y', 'people_iso_3', 'people_iso_5', 'people_iso_10', 'people_iso_15', 'people_iso_30', 'type'])
test = pd.merge(test, test3, on = ['id', 'sales_per_month', 'region', 'locality', 'x', 'y', 'people_iso_3', 'people_iso_5', 'people_iso_10', 'people_iso_15', 'people_iso_30', 'type'])
test = pd.merge(test, test4, on = ['id', 'sales_per_month', 'region', 'locality', 'x', 'y', 'people_iso_3', 'people_iso_5', 'people_iso_10', 'people_iso_15', 'people_iso_30', 'type'])
test = pd.merge(test, test5, on = ['id', 'sales_per_month', 'region', 'locality', 'x', 'y', 'people_iso_3', 'people_iso_5', 'people_iso_10', 'people_iso_15', 'people_iso_30', 'type'])

list_idx_test = list(test.id)


test.fclass.fillna('unknown', inplace=True) 
test

,id,sales_per_month,region,locality,x,y,people_iso_3,people_iso_5,people_iso_10,people_iso_15,...,commercial_density_300,commercial_density_500,geometry,index_right,fclass,count_railway_station_iso_3,count_railway_station_iso_5,count_railway_station_iso_10,count_railway_station_iso_15,count_railway_station_iso_30
0,8319,NaN,Московская область,Домодедово,37.762291,55.450032,470,506,1353,5967,...,17,23,POINT (37.762291 55.450032),1713613.0,residential,0.0,0.0,0.0,0.0,1.0
1,10248,NaN,Ростовская область,Таганрог,38.921404,47.270064,42,138,838,6112,...,0,0,POINT (38.921404 47.270064),NaN,unknown,0.0,0.0,0.0,0.0,1.0
2,22502,NaN,Ростовская область,посёлок Матвеев Курган,38.859816,47.565717,18,60,524,2437,...,16,25,POINT (38.859816 47.565717),3855835.0,residential,0.0,0.0,0.0,1.0,1.0
3,24497,NaN,Москва,Москва,37.720271,55.597304,716,2917,12095,24653,...,10,24,POINT (37.720271 55.597304),1174896.0,residential,0.0,0.0,0.0,0.0,1.0
4,23685,NaN,Ростовская область,село Авило-Успенка,38.674475,47.692474,0,3,30,108,...,1,2,POINT (38.674475 47.692474),NaN,unknown,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17426,18085,NaN,Московская область,Воскресенск,38.693206,55.310078,0,0,0,0,...,3,4,POINT (38.693206 55.310078),1035258.0,industrial,0.0,0.0,0.0,0.0,0.0
17427,23428,NaN,Ереван,Ереван,44.525006,40.131853,838,1136,9215,20182,...,16,17,POINT (44.525006 40.131853),23380.0,residential,0.0,0.0,0.0,0.0,0.0
17428,11862,NaN,Лорийская область,Ванадзор,44.483527,40.811495,1234,3135,15032,28339,...,34,63,POINT (44.483527 40.811495),15925.0,residential,0.0,0.0,0.0,1.0,1.0
17429,10382,NaN,Ереван,Ереван,44.525365,40.207058,1942,5353,23017,51741,...,23,72,POINT (44.525365 40.207058),5104.0,residential,0.0,0.0,0.0,0.0,0.0
17430,23737,NaN,Пензенская область,село Кондоль,45.056908,52.819605,0,0,10,389,...,1,2,POINT (45.056908 52.819605),4973563.0,residential,0.0,0.0,0.0,0.0,0.0

In [4]:
label_encoder = LabelEncoder()
label_encoder.fit(pd.concat([test['fclass'], data['fclass']]))
test['fclass_encoded'] =label_encoder.transform(test['fclass'])
data['fclass_encoded'] =label_encoder.transform(data['fclass'])

label_encoder = LabelEncoder()
label_encoder.fit(pd.concat([test['locality'], data['locality']]))
test['locality_encoded'] =label_encoder.transform(test['locality'])
data['locality_encoded'] =label_encoder.transform(data['locality'])

label_encoder = LabelEncoder()
label_encoder.fit(pd.concat([test['region'], data['region']]))
test['region_encoded'] =label_encoder.transform(test['region'])
data['region_encoded'] =label_encoder.transform(data['region'])

In [5]:
whole_data = pd.concat([data, test], ignore_index = True)
whole_data

,id,sales_per_month,region,locality,x,y,people_iso_3,people_iso_5,people_iso_10,people_iso_15,...,index_right,fclass,count_railway_station_iso_3,count_railway_station_iso_5,count_railway_station_iso_10,count_railway_station_iso_15,count_railway_station_iso_30,fclass_encoded,locality_encoded,region_encoded
0,18398,2538.0,Челябинская область,Озерск,60.692229,55.761933,971,2093,10439,23027,...,NaN,unknown,0.0,0.0,0.0,0.0,0.0,15,785,110
1,14532,1645.0,Москва,Москва,37.678559,55.702931,840,2329,15949,35836,...,598516.0,residential,0.0,0.0,0.0,1.0,3.0,12,682,56
2,23801,3176.0,Липецкая область,Липецк,39.524007,52.589588,690,4012,22279,47864,...,777617.0,residential,0.0,0.0,0.0,0.0,0.0,12,597,49
3,9791,4759.0,Краснодарский край,посёлок городского типа Сириус,39.957405,43.414255,49,515,2699,3710,...,3681669.0,residential,0.0,0.0,0.0,0.0,1.0,12,2417,43
4,3004,2051.0,Тюменская область,Сургут,73.450188,61.237837,1416,5619,23135,50801,...,4153109.0,residential,0.0,0.0,0.0,0.0,0.0,12,1033,105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26012,18085,NaN,Московская область,Воскресенск,38.693206,55.310078,0,0,0,0,...,1035258.0,industrial,0.0,0.0,0.0,0.0,0.0,7,215,57
26013,23428,NaN,Ереван,Ереван,44.525006,40.131853,838,1136,9215,20182,...,23380.0,residential,0.0,0.0,0.0,0.0,0.0,12,325,26
26014,11862,NaN,Лорийская область,Ванадзор,44.483527,40.811495,1234,3135,15032,28339,...,15925.0,residential,0.0,0.0,0.0,1.0,1.0,12,170,50
26015,10382,NaN,Ереван,Ереван,44.525365,40.207058,1942,5353,23017,51741,...,5104.0,residential,0.0,0.0,0.0,0.0,0.0,12,325,26
26016,23737,NaN,Пензенская область,село Кондоль,45.056908,52.819605,0,0,10,389,...,4973563.0,residential,0.0,0.0,0.0,0.0,0.0,12,3276,66

In [6]:
#fixing nan regions
no_region_idx = whole_data[whole_data.region.isna()].index
whole_data.at[no_region_idx[0], 'region'] = 'Карагандинская область'
whole_data.at[no_region_idx[1], 'region'] = 'Акмолинская область'

In [7]:
stats = pd.read_csv('stats1.csv')
stats.region = stats.region.apply(lambda x: x.replace('_Вайоцдзорская область', 'Вайоцдзорская область'))

In [8]:
whole_data = pd.merge(whole_data, stats,on ='region', how='left')
whole_data

,id,sales_per_month,region,locality,x,y,people_iso_3,people_iso_5,people_iso_10,people_iso_15,...,count_railway_station_iso_15,count_railway_station_iso_30,fclass_encoded,locality_encoded,region_encoded,Population,unemployment_lvl,salary,migration_rate,country
0,18398,2538.0,Челябинская область,Озерск,60.692229,55.761933,971,2093,10439,23027,...,0.0,0.0,15,785,110,3418606,5.1,50104.4,0.050000,Россия
1,14532,1645.0,Москва,Москва,37.678559,55.702931,840,2329,15949,35836,...,1.0,3.0,12,682,56,12635466,1.4,125637.6,70.900000,Россия
2,23801,3176.0,Липецкая область,Липецк,39.524007,52.589588,690,4012,22279,47864,...,0.0,0.0,12,597,49,1113680,3.7,46711.4,-24.200000,Россия
3,9791,4759.0,Краснодарский край,посёлок городского типа Сириус,39.957405,43.414255,49,515,2699,3710,...,0.0,1.0,12,2417,43,5687378,4.8,50251.9,20.390000,Россия
4,3004,2051.0,Тюменская область,Сургут,73.450188,61.237837,1416,5619,23135,50801,...,0.0,0.0,12,1033,105,3806505,3.0,94961.9,29.000000,Россия
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26012,18085,NaN,Московская область,Воскресенск,38.693206,55.310078,0,0,0,0,...,0.0,0.0,7,215,57,7768878,2.7,70704.6,89.500000,Россия
26013,23428,NaN,Ереван,Ереван,44.525006,40.131853,838,1136,9215,20182,...,0.0,0.0,12,325,26,1092000,19.8,39924.6,11.133228,Армения
26014,11862,NaN,Лорийская область,Ванадзор,44.483527,40.811495,1234,3135,15032,28339,...,1.0,1.0,12,170,50,212600,23.8,20617.8,11.133228,Армения
26015,10382,NaN,Ереван,Ереван,44.525365,40.207058,1942,5353,23017,51741,...,0.0,0.0,12,325,26,1092000,19.8,39924.6,11.133228,Армения
26016,23737,NaN,Пензенская область,село Кондоль,45.056908,52.819605,0,0,10,389,...,0.0,0.0,12,3276,66,1274062,4.3,41307.2,-26.600000,Россия

In [9]:
whole_data[whole_data.Population.isna()]

Empty DataFrame
Columns: [id, sales_per_month, region, locality, x, y, people_iso_3, people_iso_5, people_iso_10, people_iso_15, people_iso_30, type, count_pvz_iso_3, count_pvz_iso_5, count_pvz_iso_10, count_pvz_iso_15, count_pvz_iso_30, pop_per_pvz_iso3, pop_per_pvz_iso5, pop_per_pvz_iso10, pop_per_pvz_iso15, pop_per_pvz_iso30, Nearest_Neighbor, Distance, commercial_density_300, commercial_density_500, geometry, index_right, fclass, count_railway_station_iso_3, count_railway_station_iso_5, count_railway_station_iso_10, count_railway_station_iso_15, count_railway_station_iso_30, fclass_encoded, locality_encoded, region_encoded, Population, unemployment_lvl, salary, migration_rate, country]
Index: []

[0 rows x 42 columns]

In [10]:
for i in [3,5,10,15,30]:
    whole_data['pop_iso%s_per_region' %i] = whole_data['people_iso_%s' %i] / whole_data['Population'] * 1000

In [11]:
whole_data['country_encoded'] = label_encoder.fit_transform(whole_data['country'])

In [12]:
whole_data

,id,sales_per_month,region,locality,x,y,people_iso_3,people_iso_5,people_iso_10,people_iso_15,...,unemployment_lvl,salary,migration_rate,country,pop_iso3_per_region,pop_iso5_per_region,pop_iso10_per_region,pop_iso15_per_region,pop_iso30_per_region,country_encoded
0,18398,2538.0,Челябинская область,Озерск,60.692229,55.761933,971,2093,10439,23027,...,5.1,50104.4,0.050000,Россия,0.284034,0.612238,3.053584,6.735786,21.551474,3
1,14532,1645.0,Москва,Москва,37.678559,55.702931,840,2329,15949,35836,...,1.4,125637.6,70.900000,Россия,0.066480,0.184322,1.262241,2.836144,5.317176,3
2,23801,3176.0,Липецкая область,Липецк,39.524007,52.589588,690,4012,22279,47864,...,3.7,46711.4,-24.200000,Россия,0.619568,3.602471,20.004849,42.978234,146.959629,3
3,9791,4759.0,Краснодарский край,посёлок городского типа Сириус,39.957405,43.414255,49,515,2699,3710,...,4.8,50251.9,20.390000,Россия,0.008616,0.090551,0.474560,0.652322,1.661398,3
4,3004,2051.0,Тюменская область,Сургут,73.450188,61.237837,1416,5619,23135,50801,...,3.0,94961.9,29.000000,Россия,0.371995,1.476157,6.077754,13.345838,29.084160,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26012,18085,NaN,Московская область,Воскресенск,38.693206,55.310078,0,0,0,0,...,2.7,70704.6,89.500000,Россия,0.000000,0.000000,0.000000,0.000000,1.036572,3
26013,23428,NaN,Ереван,Ереван,44.525006,40.131853,838,1136,9215,20182,...,19.8,39924.6,11.133228,Армения,0.767399,1.040293,8.438645,18.481685,43.241758,0
26014,11862,NaN,Лорийская область,Ванадзор,44.483527,40.811495,1234,3135,15032,28339,...,23.8,20617.8,11.133228,Армения,5.804327,14.746002,70.705550,133.297272,227.351834,0
26015,10382,NaN,Ереван,Ереван,44.525365,40.207058,1942,5353,23017,51741,...,19.8,39924.6,11.133228,Армения,1.778388,4.902015,21.077839,47.381868,134.630037,0
26016,23737,NaN,Пензенская область,село Кондоль,45.056908,52.819605,0,0,10,389,...,4.3,41307.2,-26.600000,Россия,0.000000,0.000000,0.007849,0.305323,1.556439,3

In [13]:
whole_data.to_csv('whole_data.csv', index = False)